/* tslint:disable */
/* eslint-disable */
export function __wbg_bruteforceindexusize_free(a: number): void;
export function bruteforceindexusize_build(a: number, b: number, c: number): number;
export function bruteforceindexusize_add(a: number, b: number, c: number, d: number): number;
export function bruteforceindexusize_clear(a: number): number;
export function bruteforceindexusize_size(a: number): number;
export function bruteforceindexusize_bulk_add(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function bruteforceindexusize_search(a: number, b: number, c: number, d: number, e: number): void;
export function bruteforceindexusize_name(a: number, b: number): void;
export function bruteforceindexusize_dump_index(a: number, b: number): void;
export function bruteforceindexusize_load_index(a: number, b: number): number;
export function bruteforceindexusize_new(a: number): number;
export function __wbg_hnswindexusize_free(a: number): void;
export function hnswindexusize_build(a: number, b: number, c: number): number;
export function hnswindexusize_add(a: number, b: number, c: number, d: number): number;
export function hnswindexusize_bulk_add(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function hnswindexusize_search(a: number, b: number, c: number, d: number, e: number): void;
export function hnswindexusize_name(a: number, b: number): void;
export function hnswindexusize_dump_index(a: number, b: number): void;
export function hnswindexusize_load_index(a: number, b: number): number;
export function hnswindexusize_new(a: number, b: number, c: number, d: number, e: number, f: number, g: number): number;
export function __wbg_pqindexusize_free(a: number): void;
export function pqindexusize_build(a: number, b: number, c: number): number;
export function pqindexusize_add(a: number, b: number, c: number, d: number): number;
export function pqindexusize_bulk_add(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function pqindexusize_search(a: number, b: number, c: number, d: number, e: number): void;
export function pqindexusize_name(a: number, b: number): void;
export function pqindexusize_dump_index(a: number, b: number): void;
export function pqindexusize_load_index(a: number, b: number): number;
export function pqindexusize_new(a: number, b: number, c: number, d: number): number;
export function __wbg_ivfpqindexusize_free(a: number): void;
export function ivfpqindexusize_build(a: number, b: number, c: number): number;
export function ivfpqindexusize_add(a: number, b: number, c: number, d: number): number;
export function ivfpqindexusize_bulk_add(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function ivfpqindexusize_search(a: number, b: number, c: number, d: number, e: number): void;
export function ivfpqindexusize_name(a: number, b: number): void;
export function ivfpqindexusize_dump_index(a: number, b: number): void;
export function ivfpqindexusize_load_index(a: number, b: number): number;
export function ivfpqindexusize_new(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function __wbg_ssgindexusize_free(a: number): void;
export function ssgindexusize_build(a: number, b: number, c: number): number;
export function ssgindexusize_add(a: number, b: number, c: number, d: number): number;
export function ssgindexusize_size(a: number): number;
export function ssgindexusize_bulk_add(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function ssgindexusize_search(a: number, b: number, c: number, d: number, e: number): void;
export function ssgindexusize_name(a: number, b: number): void;
export function ssgindexusize_dump_index(a: number, b: number): void;
export function ssgindexusize_load_index(a: number, b: number): number;
export function ssgindexusize_new(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function init_env(): void;
export function hnswindexusize_clear(a: number): number;
export function hnswindexusize_size(a: number): number;
export function pqindexusize_clear(a: number): number;
export function pqindexusize_size(a: number): number;
export function ivfpqindexusize_clear(a: number): number;
export function ivfpqindexusize_size(a: number): number;
export function ssgindexusize_clear(a: number): number;
export const memory: WebAssembly.Memory;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export function __wbindgen_exn_store(a: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_thread_destroy(a: number, b: number): void;
export function __wbindgen_start(): void;
